#include "smesh_context.hpp"
#include "smesh_env.hpp"
#include "smesh_extractions.hpp"
#include "smesh_glob.hpp"
#include "smesh_mesh.hpp"
#include "smesh_path.hpp"
#include "smesh_tracer.hpp"

#include <stdio.h>

using namespace smesh;

int main(int argc, char **argv) {
    SMESH_TRACE_SCOPE("extract_sharp_features.exe");
    auto ctx = initialize_serial(argc, argv);

    if (argc != 3) {
        fprintf(stderr,
                "Usage: %s <mesh_folder> "
                "<output_folder>\n",
                argv[0]);
        return SMESH_FAILURE;
    }

    int ret = SMESH_SUCCESS;
    {
        auto mesh = Mesh::create_from_file(ctx->communicator(), Path(argv[1]));

        auto sharp_edges = extract_sharp_edges(*mesh, Env::read("SMESH_SHARP_EDGES_THRESHOLD", 0.15));

        auto sharp_corners = extract_sharp_corners(mesh->n_nodes(), sharp_edges, true);

        auto disconnected_faces = extract_disconnected_faces(*mesh, sharp_edges);

        auto output_path = Path(argv[2]);
        auto write_meta = [&](const Path &folder,
                              const char *element_type,
                              const int elem_num_nodes,
                              const ptrdiff_t n_elements,
                              const std::string &ext) {
            FILE *meta = fopen((folder / "meta.yaml").c_str(), "w");
            if (!meta) {
                fprintf(stderr, "Unable to write %s\n", (folder / "meta.yaml").c_str());
                ret = SMESH_FAILURE;
                return;
            }

            fprintf(meta, "# Automatically generated by %s\n", argv[0]);
            fprintf(meta, "elem_num_nodes: %d\n", elem_num_nodes);
            fprintf(meta, "element_type: %s\n", element_type);
            fprintf(meta, "n_elements: %ld\n", (long)n_elements);
            fprintf(meta, "elements:\n");
            for (int i = 0; i < elem_num_nodes; ++i) {
                fprintf(meta, "- i%d: i%d.%s\n", i, i, ext.c_str());
            }
            fprintf(meta, "rpath: true\n");
            fclose(meta);
        };

        create_directory(output_path);
        create_directory(output_path / ("edges"));
        create_directory(output_path / ("corners"));

        create_directory(output_path / ("disconnected_faces"));

        {
            std::string ext(TypeToString<idx_t>::value());
            write_meta(output_path / ("edges"), "BEAM2", 2, sharp_edges->extent(1), ext);
            write_meta(output_path / ("corners"), "NODE1", 1, sharp_corners->size(), ext);
            sharp_edges->to_files(output_path / ("edges/i%d." + ext));
            sharp_corners->to_file(output_path / ("corners/i0." + ext));
        }

        {
            std::string ext(TypeToString<element_idx_t>::value());
            disconnected_faces->to_file(output_path / ("disconnected_faces/i0." + ext));
        }
    }

    return ret;
}
