#include "smesh_nodeset.hpp"
#include "smesh_alloc.hpp"
#include "smesh_edgesets.hpp"
#include "smesh_file_extensions.hpp"
#include "smesh_glob.hpp"
#include "smesh_mesh.hpp"
#include "smesh_read.hpp"
#include "smesh_tracer.hpp"
#include "smesh_write.hpp"

#ifdef SMESH_ENABLE_MPI
#include "smesh_distributed_base.hpp"
#include "smesh_distributed_write.hpp"
#endif

#include <algorithm>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace smesh {

    class Nodeset::Impl final {
    public:
        std::shared_ptr<Communicator> comm;
        std::shared_ptr<Buffer<idx_t>> nodes;
        SharedBuffer<large_idx_t>      node_mapping;
    };

    Nodeset::Nodeset(const std::shared_ptr<Communicator> &comm,
                     const SharedBuffer<idx_t>           &nodes,
                     const SharedBuffer<large_idx_t>     &node_mapping)
        : impl_(std::make_unique<Impl>()) {
        impl_->comm          = comm;
        impl_->nodes         = nodes;
        impl_->node_mapping  = node_mapping;
    }

    Nodeset::Nodeset() : impl_(std::make_unique<Impl>()) {}
    Nodeset::~Nodeset() = default;

    ptrdiff_t Nodeset::size() const { return impl_->nodes ? (ptrdiff_t)impl_->nodes->size() : 0; }

    std::shared_ptr<Communicator> Nodeset::comm() const { return impl_->comm; }

    std::shared_ptr<Nodeset> Nodeset::create(const std::shared_ptr<Communicator> &comm,
                                             const SharedBuffer<idx_t>           &nodes,
                                             const SharedBuffer<large_idx_t>     &node_mapping) {
        return std::make_shared<Nodeset>(comm, nodes, node_mapping);
    }

    std::shared_ptr<Nodeset> Nodeset::create_from_file(const std::shared_ptr<Communicator> &comm,
                                                       const Path                          &path) {
        auto ret = std::make_shared<Nodeset>();
        if (ret->read(comm, path) != SMESH_SUCCESS) {
            return nullptr;
        }
        return ret;
    }

    static int parse_nodeset_meta(const Path &folder, bool *has_size, ptrdiff_t *meta_size) {
        *has_size = false;
        const Path meta = folder / "meta.yaml";
        if (!meta.exists()) {
            return SMESH_SUCCESS;
        }
        std::ifstream ifs(meta.to_string());
        if (!ifs.good()) {
            SMESH_ERROR("Unable to open nodeset meta.yaml file\n");
            return SMESH_FAILURE;
        }
        std::string line;
        while (std::getline(ifs, line)) {
            const auto hash = line.find('#');
            if (hash != std::string::npos) {
                line.resize(hash);
            }
            const auto start = line.find_first_not_of(" \t");
            if (start == std::string::npos) {
                continue;
            }
            line = line.substr(start);
            if (line.compare(0, 5, "size:") == 0) {
                *has_size  = true;
                *meta_size = static_cast<ptrdiff_t>(std::strtoll(line.c_str() + 5, nullptr, 10));
            }
        }
        return SMESH_SUCCESS;
    }

    int Nodeset::write(const Path &path) const {
        if (!comm()->rank()) {
            smesh::create_directory(path.to_string());
        }

        Path nodes_path = path / ("nodes." + std::string(TypeToString<idx_t>::value()));
        u64  n_global   = static_cast<u64>(size());

#ifdef SMESH_ENABLE_MPI
        comm()->barrier();
        if (comm()->size() > 1) {
            const u64 n_local = n_global;
            MPI_Allreduce(MPI_IN_PLACE, &n_global, 1, mpi_type<u64>(), MPI_SUM, comm()->get());

            if (impl_->node_mapping) {
                auto          out   = create_host_buffer<idx_t>(n_local);
                idx_t        *d_out = out->data();
                const large_idx_t *b_map = impl_->node_mapping->data();
                const idx_t       *b_loc = impl_->nodes->data();
                for (u64 i = 0; i < n_local; ++i) {
                    d_out[i] = (idx_t)b_map[b_loc[i]];
                }
                array_write_convert_from_extension(comm()->get(), nodes_path, d_out, n_local, n_global);
            } else {
                array_write_convert_from_extension(
                        comm()->get(), nodes_path, impl_->nodes->data(), impl_->nodes->size(), n_global);
            }
        } else
#endif
        {
            array_write(nodes_path, impl_->nodes->data(), impl_->nodes->size());
        }

        if (!comm()->rank()) {
            std::ofstream os((path / "meta.yaml").to_string());
            if (os.good()) {
                os << "# Automatically generated by smesh_nodeset.cpp\n";
                os << "size: " << n_global << "\n";
                os << "nodes: nodes." << TypeToString<idx_t>::value() << "\n";
                os << "rpath: true\n";
            } else {
                SMESH_ERROR("Unable to open nodeset meta.yaml file\n");
                return SMESH_FAILURE;
            }
        }
        return SMESH_SUCCESS;
    }

    int Nodeset::read(const std::shared_ptr<Communicator> &comm, const Path &folder) {
        SMESH_TRACE_SCOPE("Nodeset::read");
        if (comm->size() > 1) {
            SMESH_ERROR("Nodeset::read is not supported for distributed runs\n");
            return SMESH_FAILURE;
        }

        impl_->comm = comm;
        ptrdiff_t nlocal{0};
        idx_t    *nodes{nullptr};

        auto nodes_file = detect_files(folder / "nodes.*", {"raw", "int16", "int32", "int64"});
        if (nodes_file.empty()) {
            nodes_file = detect_files(folder / "nodeset.*", {"raw", "int16", "int32", "int64"});
        }
        if (nodes_file.empty()) {
            SMESH_ERROR("Unable to find nodes file in nodeset at %s\n", folder.c_str());
            return SMESH_FAILURE;
        }

        int ret = array_read_convert_from_extension(nodes_file[0], &nodes, &nlocal);
        impl_->nodes = smesh::manage_host_buffer(nlocal, nodes);

        bool      has_size  = false;
        ptrdiff_t meta_size = 0;
        if (parse_nodeset_meta(folder, &has_size, &meta_size) != SMESH_SUCCESS) {
            return SMESH_FAILURE;
        }
        if (has_size && meta_size != nlocal) {
            SMESH_ERROR("Nodeset meta size %td does not match array length %td at %s\n",
                        meta_size,
                        nlocal,
                        folder.c_str());
            ret = SMESH_FAILURE;
        }
        return ret;
    }

    int Nodeset::read_and_redistibute(const std::shared_ptr<Mesh> &mesh, const Path &path) {
#ifdef SMESH_ENABLE_MPI
        const int rank = mesh->comm()->rank();
        const int size = mesh->comm()->size();
        if (size > 1) {
            i64 n_nodes = 0;
            if (rank == 0) {
                if (read(Communicator::self(), path) != SMESH_SUCCESS) {
                    n_nodes = -1;
                } else {
                    n_nodes = static_cast<i64>(this->size());
                }
            }
            mesh->comm()->broadcast(&n_nodes, 1, 0);
            if (n_nodes < 0) {
                return SMESH_FAILURE;
            }

            impl_->comm = mesh->comm();
            auto nodes_buf = create_host_buffer<idx_t>((size_t)n_nodes);
            if (rank == 0 && n_nodes > 0) {
                std::memcpy(nodes_buf->data(), impl_->nodes->data(), (size_t)n_nodes * sizeof(idx_t));
            }
            if (n_nodes > 0) {
                mesh->comm()->broadcast(nodes_buf->data(), (int)n_nodes, 0);
            }
            impl_->nodes = nodes_buf;
            return redistribute(mesh);
        }
#endif
        if (read(mesh->comm(), path) != SMESH_SUCCESS) {
            return SMESH_FAILURE;
        }
        return redistribute(mesh);
    }

    int Nodeset::redistribute(const std::shared_ptr<Mesh> &mesh) {
        if (mesh->comm()->size() == 1) {
            return SMESH_SUCCESS;
        }

#ifdef SMESH_ENABLE_MPI
        auto dist = mesh->distributed();
        if (!dist) {
            SMESH_ERROR("Nodeset::redistribute: mesh is not distributed\n");
            return SMESH_FAILURE;
        }

        const ptrdiff_t n_owned  = dist->n_nodes_owned();
        auto            node_map = dist->node_mapping();
        if (n_owned > 0 && !node_map) {
            SMESH_ERROR("Nodeset::redistribute: mesh has no node_mapping\n");
            return SMESH_FAILURE;
        }

        large_idx_t        n_global = 0;
        const large_idx_t *d_nmap   = (n_owned > 0) ? node_map->data() : nullptr;
        if (n_owned > 0) {
            for (ptrdiff_t i = 0; i < n_owned; ++i) {
                const large_idx_t gid = d_nmap[i] + 1;
                if (gid > n_global) {
                    n_global = gid;
                }
            }
        }
        n_global = mesh->comm()->max(n_global);

        if (n_global == 0) {
            impl_->nodes        = create_host_buffer<idx_t>(0);
            impl_->node_mapping = node_map;
            return SMESH_SUCCESS;
        }

        auto  invert = create_host_buffer<idx_t>((size_t)n_global);
        idx_t *d_inv = invert->data();
        for (large_idx_t i = 0; i < n_global; ++i) {
            d_inv[i] = invalid_idx<idx_t>();
        }
        for (ptrdiff_t i = 0; i < n_owned; ++i) {
            const large_idx_t serial_id = d_nmap[i];
            if (serial_id >= 0 && serial_id < n_global) {
                d_inv[serial_id] = (idx_t)i;
            }
        }

        const ptrdiff_t n_ns  = size();
        const idx_t    *nodes = impl_->nodes->data();

        ptrdiff_t n_keep = 0;
        for (ptrdiff_t i = 0; i < n_ns; ++i) {
            const large_idx_t serial = (large_idx_t)nodes[i];
            if (serial >= 0 && serial < n_global && d_inv[serial] != invalid_idx<idx_t>()) {
                ++n_keep;
            }
        }

        auto   new_nodes = create_host_buffer<idx_t>((size_t)n_keep);
        idx_t *d_nn      = n_keep > 0 ? new_nodes->data() : nullptr;
        ptrdiff_t w      = 0;
        for (ptrdiff_t i = 0; i < n_ns; ++i) {
            const large_idx_t serial = (large_idx_t)nodes[i];
            if (serial >= 0 && serial < n_global) {
                const idx_t local_n = d_inv[serial];
                if (local_n != invalid_idx<idx_t>()) {
                    d_nn[w++] = local_n;
                }
            }
        }

        impl_->nodes        = new_nodes;
        impl_->node_mapping = node_map;
        return SMESH_SUCCESS;
#endif

        SMESH_ERROR("Nodeset::redistribute is not supported for distributed runs\n");
        return SMESH_FAILURE;
    }

    std::shared_ptr<Buffer<idx_t>> Nodeset::nodes() const { return impl_->nodes; }
    SharedBuffer<large_idx_t>      Nodeset::node_mapping() const { return impl_->node_mapping; }

    int Nodeset::remap_nodes(const idx_t *old_to_new, ptrdiff_t n) {
        if (!old_to_new || n < 0 || !impl_->nodes) {
            SMESH_ERROR("Nodeset::remap_nodes: invalid arguments\n");
            return SMESH_FAILURE;
        }
        if (impl_->nodes->mem_space() != MEMORY_SPACE_HOST) {
            SMESH_ERROR("Nodeset::remap_nodes requires host nodes buffer\n");
            return SMESH_FAILURE;
        }
        auto            p   = impl_->nodes->data();
        const ptrdiff_t nns = size();
        for (ptrdiff_t i = 0; i < nns; ++i) {
            const idx_t old = p[i];
            if (old < 0 || static_cast<ptrdiff_t>(old) >= n) {
                SMESH_ERROR("Nodeset::remap_nodes: node %td out of range [0, %td)\n",
                            static_cast<ptrdiff_t>(old),
                            n);
                return SMESH_FAILURE;
            }
            p[i] = old_to_new[old];
        }
        return SMESH_SUCCESS;
    }

    std::shared_ptr<Nodeset> create_nodeset_from_edgeset(const std::shared_ptr<Mesh>    &mesh,
                                                         const std::shared_ptr<Edgeset> &edgeset) {
        if (!mesh || !edgeset) {
            return nullptr;
        }
        auto block = mesh->block(edgeset->block_id());
        if (!block) {
            SMESH_ERROR("create_nodeset_from_edgeset: invalid block_id %d\n", (int)edgeset->block_id());
            return nullptr;
        }
        ptrdiff_t n_nodes = 0;
        idx_t    *nodes   = nullptr;
        const ptrdiff_t n = edgeset->size();
        if (extract_nodeset_from_edgeset(block->element_type(),
                                         block->elements()->data(),
                                         n,
                                         n > 0 ? edgeset->parent()->data() : nullptr,
                                         n > 0 ? edgeset->lei()->data() : nullptr,
                                         &n_nodes,
                                         &nodes) != SMESH_SUCCESS) {
            return nullptr;
        }
        SharedBuffer<large_idx_t> mapping = nullptr;
        if (mesh->is_distributed() && mesh->distributed()) {
            mapping = mesh->distributed()->node_mapping();
        }
        return Nodeset::create(mesh->comm(), manage_host_buffer<idx_t>(n_nodes, nodes), mapping);
    }

    std::shared_ptr<Nodeset> map_nodeset_through_refine(const std::shared_ptr<Mesh>    &coarse_mesh,
                                                        const std::shared_ptr<Nodeset> &coarse_ns,
                                                        const std::shared_ptr<Mesh>    &fine_mesh) {
        if (!coarse_mesh || !coarse_ns || !fine_mesh) {
            SMESH_ERROR("map_nodeset_through_refine: null argument\n");
            return nullptr;
        }

        const ptrdiff_t n     = coarse_ns->size();
        const idx_t    *nodes = n > 0 ? coarse_ns->nodes()->data() : nullptr;
        const ptrdiff_t n_coarse_nodes = coarse_mesh->n_nodes();
        const ptrdiff_t n_fine_nodes   = fine_mesh->n_nodes();

        SharedBuffer<large_idx_t> mapping = nullptr;
#ifdef SMESH_ENABLE_MPI
        if (fine_mesh->is_distributed() && fine_mesh->distributed()) {
            mapping = fine_mesh->distributed()->node_mapping();
        } else
#endif
            if (coarse_ns->node_mapping()) {
            const ptrdiff_t nm = coarse_ns->node_mapping()->size();
            mapping            = create_host_buffer<large_idx_t>((size_t)nm);
            if (nm > 0) {
                std::memcpy(mapping->data(), coarse_ns->node_mapping()->data(), (size_t)nm * sizeof(large_idx_t));
            }
        }

#ifdef SMESH_ENABLE_MPI
        if (coarse_mesh->is_distributed() && fine_mesh->is_distributed()) {
            auto cdist = coarse_mesh->distributed();
            auto fdist = fine_mesh->distributed();
            if (!cdist || !fdist || !cdist->node_mapping() || !fdist->node_mapping()) {
                fprintf(stderr, "map_nodeset_through_refine: distributed mesh is missing node_mapping\n");
                return nullptr;
            }
            const large_idx_t *c_map = cdist->node_mapping()->data();
            const large_idx_t *f_map = fdist->node_mapping()->data();
            const large_idx_t  n_fg  = (large_idx_t)fdist->n_nodes_global();
            std::vector<idx_t> inv((size_t)std::max<large_idx_t>(n_fg, 1), invalid_idx<idx_t>());
            for (ptrdiff_t i = 0; i < n_fine_nodes; ++i) {
                const large_idx_t g = f_map[i];
                if (g >= 0 && g < n_fg) {
                    inv[(size_t)g] = (idx_t)i;
                }
            }
            ptrdiff_t n_keep = 0;
            for (ptrdiff_t i = 0; i < n; ++i) {
                const idx_t lid = nodes[i];
                if (lid < 0 || (ptrdiff_t)lid >= n_coarse_nodes) {
                    SMESH_ERROR("map_nodeset_through_refine: node id out of range\n");
                    return nullptr;
                }
                const large_idx_t g = c_map[lid];
                if (g >= 0 && g < n_fg && inv[(size_t)g] != invalid_idx<idx_t>()) {
                    ++n_keep;
                }
            }
            auto out = create_host_buffer<idx_t>((size_t)n_keep);
            idx_t *d = n_keep > 0 ? out->data() : nullptr;
            ptrdiff_t w = 0;
            for (ptrdiff_t i = 0; i < n; ++i) {
                const large_idx_t g = c_map[nodes[i]];
                if (g >= 0 && g < n_fg && inv[(size_t)g] != invalid_idx<idx_t>()) {
                    d[w++] = inv[(size_t)g];
                }
            }
            return Nodeset::create(fine_mesh->comm(), out, mapping);
        }
#endif

        auto out = create_host_buffer<idx_t>((size_t)n);
        if (n > 0) {
            for (ptrdiff_t i = 0; i < n; ++i) {
                const idx_t lid = nodes[i];
                if (lid < 0 || (ptrdiff_t)lid >= n_coarse_nodes || (ptrdiff_t)lid >= n_fine_nodes) {
                    SMESH_ERROR("map_nodeset_through_refine: node id out of range\n");
                    return nullptr;
                }
                out->data()[i] = lid;
            }
        }
        return Nodeset::create(fine_mesh->comm(), out, mapping);
    }

    void Nodeset::print(std::ostream &os) const {
        os << "Nodeset size: " << size() << "\n";
        if (nodes()) {
            nodes()->print(os);
        }
    }

}  // namespace smesh
