#include "smesh_elem_type.hpp"
#include "smesh_glob.hpp"
#include "smesh_types.hpp"
#include "smesh_write.impl.hpp"

#include <string_view>
#include <vector>

namespace smesh {
int mesh_write_yaml_basic(const Path &path, enum ElemType element_type,
                          const ptrdiff_t n_elements, const int spatial_dim,
                          const ptrdiff_t n_nodes) {
  if (smesh::create_directory(path.to_string()) != SMESH_SUCCESS) {
    return SMESH_FAILURE;
  }

  static constexpr char xyz[3] = {'x', 'y', 'z'};

  const Path meta_path = path / "meta.yaml";
  FILE *meta_file = fopen(meta_path.c_str(), "w");
  if (!meta_file) {
    SMESH_ERROR("mesh_write_yaml_basic: Unable to write file %s\n",
                meta_path.c_str());
    return SMESH_FAILURE;
  }

  const int nxe = elem_num_nodes(element_type);

  fprintf(meta_file, "# smesh mesh meta file\n");
  fprintf(meta_file, "spatial_dimension: %d\n", spatial_dim);
  fprintf(meta_file, "elem_num_nodes: %d\n", nxe);
  fprintf(meta_file, "element_type: %s\n", type_to_string(element_type));
  fprintf(meta_file, "n_elements: %ld\n", (long)n_elements);
  fprintf(meta_file, "n_nodes: %ld\n", (long)n_nodes);

  fprintf(meta_file, "elements:\n");
  for (int d = 0; d < nxe; ++d) {
    fprintf(meta_file, "- i%d: i%d.raw\n", d, d);
  }

  fprintf(meta_file, "points:\n");
  for (int d = 0; d < spatial_dim; d++) {
    fprintf(meta_file, "- %c: %c.raw\n", xyz[d], xyz[d]);
  }

  fprintf(meta_file, "rpath: true\n");
  fclose(meta_file);
  return SMESH_SUCCESS;
}

int mesh_multiblock_write_yaml(const Path &path, const uint16_t n_blocks,
                               const std::vector<std::string_view> &block_names,
                               const std::vector<enum ElemType> &element_types,
                               const std::vector<ptrdiff_t> &n_elements,
                               const int spatial_dim, const ptrdiff_t n_nodes) {
  if (smesh::create_directory(path.to_string()) != SMESH_SUCCESS) {
    return SMESH_FAILURE;
  }

  static constexpr char xyz[3] = {'x', 'y', 'z'};

  const Path meta_path = path / "meta.yaml";
  FILE *meta_file = fopen(meta_path.c_str(), "w");
  if (!meta_file) {
    SMESH_ERROR("mesh_multiblock_write_yaml: Unable to write file %s\n",
                meta_path.c_str());
    return SMESH_FAILURE;
  }

  fprintf(meta_file,
          "# SMESH mesh meta file (generated by sfem_mesh_write.c)\n");
  fprintf(meta_file, "spatial_dimension: %d\n", spatial_dim);
  fprintf(meta_file, "n_blocks: %d\n", n_blocks);
  fprintf(meta_file, "blocks:\n");

  for (int b = 0; b < n_blocks; ++b) {
    int nxe = elem_num_nodes(element_types[b]);
    fprintf(meta_file, "- name: %s\n", block_names[b].data());
    fprintf(meta_file, "  element_type: %s\n",
            type_to_string(element_types[b]));
    fprintf(meta_file, "  elem_num_nodes: %d\n", nxe);
    fprintf(meta_file, "  n_elements: %ld\n", n_elements[b]);
    fprintf(meta_file, "  elements:\n");
    for (int d = 0; d < nxe; ++d) {
      fprintf(meta_file, "  - i%d: blocks/%d/i%d.raw\n", d, b, d);
    }
  }

  fprintf(meta_file, "n_nodes: %ld\n", (long)n_nodes);
  fprintf(meta_file, "points:\n");
  for (int d = 0; d < spatial_dim; d++) {
    fprintf(meta_file, "- %c: %c.raw\n", xyz[d], xyz[d]);
  }

  fprintf(meta_file, "rpath: true\n");
  fclose(meta_file);

  return SMESH_SUCCESS;
}

} // namespace smesh

#define SMESH_EXPLICIT_INSTANTIATE_MESH_BLOCK_TO_FOLDER(IDX_T)                 \
  template int mesh_block_to_folder<IDX_T>(                                    \
      const Path &, int, const ptrdiff_t,                                      \
      IDX_T *const SMESH_RESTRICT *const SMESH_RESTRICT);

#define SMESH_EXPLICIT_INSTANTIATE_MESH_COORDINATES_TO_FOLDER(GEOM_T)          \
  template int mesh_coordinates_to_folder<GEOM_T>(                             \
      const Path &, int, const ptrdiff_t,                                      \
      GEOM_T *const SMESH_RESTRICT *const SMESH_RESTRICT);

#define SMESH_EXPLICIT_INSTANTIATE_MESH_TO_FOLDER(IDX_T, GEOM_T)               \
  template int mesh_to_folder<IDX_T, GEOM_T>(                                  \
      const Path &, enum ElemType, const ptrdiff_t,                            \
      IDX_T *const SMESH_RESTRICT *const SMESH_RESTRICT, const int,            \
      const ptrdiff_t, GEOM_T *const SMESH_RESTRICT *const SMESH_RESTRICT);

#define SMESH_EXPLICIT_INSTANTIATE_MESH_MULTIBLOCK_TO_FOLDER(IDX_T, GEOM_T)    \
  template int mesh_multiblock_to_folder<IDX_T, GEOM_T>(                       \
      const std::vector<std::string_view> &,                                   \
      const std::vector<enum ElemType> &, const std::vector<ptrdiff_t> &,      \
      IDX_T **const[], const int, const ptrdiff_t, GEOM_T **const);

namespace smesh {
SMESH_EXPLICIT_INSTANTIATE_MESH_BLOCK_TO_FOLDER(i32);
SMESH_EXPLICIT_INSTANTIATE_MESH_BLOCK_TO_FOLDER(i64);
SMESH_EXPLICIT_INSTANTIATE_MESH_BLOCK_TO_FOLDER(i16);

SMESH_EXPLICIT_INSTANTIATE_MESH_COORDINATES_TO_FOLDER(f32);

SMESH_EXPLICIT_INSTANTIATE_MESH_TO_FOLDER(i32, f32);
SMESH_EXPLICIT_INSTANTIATE_MESH_TO_FOLDER(i64, f32);
SMESH_EXPLICIT_INSTANTIATE_MESH_TO_FOLDER(i16, f32);

SMESH_EXPLICIT_INSTANTIATE_MESH_MULTIBLOCK_TO_FOLDER(i32, f32);
SMESH_EXPLICIT_INSTANTIATE_MESH_MULTIBLOCK_TO_FOLDER(i64, f32);
SMESH_EXPLICIT_INSTANTIATE_MESH_MULTIBLOCK_TO_FOLDER(i16, f32);
} // namespace smesh

#undef SMESH_EXPLICIT_INSTANTIATE_MESH_BLOCK_TO_FOLDER
#undef SMESH_EXPLICIT_INSTANTIATE_MESH_COORDINATES_TO_FOLDER
#undef SMESH_EXPLICIT_INSTANTIATE_MESH_TO_FOLDER
#undef SMESH_EXPLICIT_INSTANTIATE_MESH_MULTIBLOCK_TO_FOLDER
